# 商品服务端
eureka:
    client:
        service-url:
            defaultZone: http://localhost:8762/eureka/
        #表示eureka client间隔多久去拉取服务注册信息，默认为30秒
        registryFetchIntervalSeconds: 5
    instance:
        # IP
        hostname: localhost
        instance-id: ${spring.application.name}:${server.port}:@project.version@
        #表示eureka client发送心跳给server端的频率，默认为30秒
        leaseRenewalIntervalInSeconds: 10
        #健康检查的地址（依赖spring-boot-starter-actuator）
        health-check-url-path: /actuator/health
# MyBatis配置
mybatis:
    mapper-locations: classpath*:/mapper/**/*.xml
    type-aliases-package: com.leigq.commodity.domain.mapper
    # 设置自动驼峰命名转换
    configuration:
      mapUnderscoreToCamelCase: true
      # 使用mybatis插入自增主键ID的数据后返回自增的ID，配合keyProperty="id"使用
      use-generated-keys: true

# 服务器配置
server:
    # 建议不要直接写死，可以在VM options中通过-DServer.port=8080配置
    port: 8080
    tomcat:
        uri-encoding: UTF-8
spring:
    application:
        name: commodity
    # 数据源、数据库连接池druid配置
    datasource:
        connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000;config.decrypt=true;config.decrypt.key=MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAKPYsCl3alwZlRb1vKoFdVu0LP3Nm/+vH5iOWxI83pkUbrQc13Lxz/VT3D+H+ziaUpUsA+ZjG4iZGTDJWZnP8kcCAwEAAQ==
        driver-class-name: com.mysql.jdbc.Driver
        filters: config,stat,wall,slf4j
        initialSize: 5
        maxActive: 20
        maxPoolPreparedStatementPerConnectionSize: 20
        maxWait: 60000
        minEvictableIdleTimeMillis: 300000
        minIdle: 5
        password: kGJF6c+pzVsf49LGs01ss0yijBGXIpNEp20cMkNCQo3ONaeMNPeoW9M89v+nGeiWs95/D2Ms59uGyydDGUWpmg==
        poolPreparedStatements: true
        testOnBorrow: false
        testOnReturn: false
        testWhileIdle: true
        timeBetweenEvictionRunsMillis: 60000
        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:mysql://localhost:3306/spring_cloud?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=true&serverTimezone=UTC
        username: root
        validationQuery: SELECT 1 FROM DUAL

# 分页插件
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql

# 端点监控
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS